config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:show, :edit, :update, :destroy]
  get 'users' => 'users#dummy'
  root 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#new_guest' # ゲストログイン用
  resources :cooks do
    collection do
      get 'net'
      get 'plate'
      get 'pan'
      get 'dutch_oven'
      get 'pot'
      get 'other'
      get 'rank'
      get 'weekly_rank'
      get 'bookmark'
      get 'search_index'
    end
    resource :likes, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  resources :notifications, only: [:index] do
    collection do
      delete "all_destroy"
    end
  end
  resources :articles, only: [:index, :show]
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :user
  attachment :image

  has_many :materials
  accepts_nested_attributes_for :materials
  scope :sorted, -> { order(updated_at: :desc) }
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_cooks, through: :bookmarks, source: :user
  has_many :notifications, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :comment
    validates :cooking_time
    validates :cook_genre
    validates :cook_item
    validates :image
    validates :cooking_method
  end
  validates :cooking_time, presence: true, numericality: { only_integer: true }

  enum cook_genre: { meet: 0, fish: 1, vegetables: 2, noodle: 3, rice: 4, soup: 5, other: 6 }
  enum cook_item: { net: 0, plate: 1, pan: 2, dutch_oven: 3, pot: 4, other: 5 }, _prefix: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.ranks
    find(Like.group(:cook_id).order(Arel.sql('count(cook_id) desc')).limit(9).pluck(:cook_id))
  end

  def self.last_week
    # 料理テーブルといいねテーブルを結合し、特定期間のいいねがついた料理を取得。
    today = Time.current
    joins(:likes).where(
      likes: { created_at: today.prev_week..today.prev_week(:sunday) }
    ).group(:id).order("count(*) desc").limit(9)
  end

  def self.ranks_top
    find(Like.group(:cook_id).order(Arel.sql('count(cook_id) desc')).limit(3).pluck(:cook_id))
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  # 通知作成のために定義
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    already_like_check = Notification.where(
      [
        "visitor_id = ? and visited_id = ? and cook_id = ? and action = ? ",
        current_user.id, user_id, id, 'like',
      ]
    )
    # いいねされていない場合のみ、通知レコードを作成
    return unless already_like_check.blank?
    notification = current_user.active_notifications.new(
      cook_id: id,
      visited_id: user_id,
      action: 'like'
    )
    notification.update_is_checked_and_save # Notificationモデルに定義
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :authenticate_user!, only: [:bookmark, :rank]
  before_action :confirm_user, only: [:edit, :update, :destroy]

  def confirm_user
    cook = Cook.find(params[:id])
    unless cook.user_id == current_user.id
      redirect_to root_path
    end
  end

  def new
    @cook = Cook.new
    8.times { @cook.materials.build }
  end

  def create
    @cook = Cook.new(cook_params)
    @cook.user_id = current_user.id
    if @cook.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def index
    @cooks = Cook.page(params[:page]).per(9).sorted
  end

  def net
    @cooks_net = Cook.page(params[:page]).where(cook_item: 0).per(9).sorted
  end

  def plate
    @cooks_plate = Cook.page(params[:page]).where(cook_item: 1).per(9).sorted
  end

  def pan
    @cooks_pan = Cook.page(params[:page]).where(cook_item: 2).per(9).sorted
  end

  def dutch_oven
    @cooks_dutch_oven = Cook.page(params[:page]).where(cook_item: 3).per(9).sorted
  end

  def pot
    @cooks_pot = Cook.page(params[:page]).where(cook_item: 4).per(9).sorted
  end

  def other
    @cooks_other = Cook.page(params[:page]).where(cook_item: 5).per(9).sorted
  end

  def rank
    @ranks = Cook.ranks # モデルに定義記載
  end

  def weekly_rank
    @ranks = Cook.last_week # モデルに定義記載
  end

  def bookmark
    @bookmarks = current_user.bookmark_cooks.order(created_at: :desc)
  end

  def search_index
  end

  def show
    @cook = Cook.find(params[:id])
    # 値が入っているものだけを取り出している
    @materials = @cook.materials.where.not(material: "")
  end

  def edit
    @cook = Cook.find(params[:id])
  end

  def update
    @cook = Cook.find(params[:id])
    if @cook.update(cook_params)
      redirect_to cook_path(@cook)
    else
      render 'edit'
    end
  end

  def destroy
    @cook = Cook.find(params[:id])
    @cook.destroy
    redirect_to user_path(current_user)
  end

  private

  def cook_params
    params.require(:cook).permit(
      :name,
      :cooking_time,
      :cook_genre,
      :cook_item,
      :cooking_method,
      :image,
      :comment,
      materials_attributes: [:material, :qty, :id]
    )
  end
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/bookmark.html.slim
- content_for(:title, 'お気に入り | CamFoo')
div.bookmark-image
  div.bg-rgba
    h2 Bookmark
div.container
  div.row
    div.col-10.offset-1
      - if @bookmarks.present?
        table.table.table-striped.text-white.text-center
          thead
              tr
                th
                th 投稿者
                th 料理名
                th
          tbody
            - @bookmarks.each do |cook|
              tr
                td
                  = attachment_image_tag cook.user, :account_image, :fill, 60, 60, fallback: "no_image.jpg", class: "mt-0 no-image";
                td.pt-4
                  = link_to cook.user do
                    = cook.user.account
                td.pt-4
                  = cook.name
                td.pt-4
                  = link_to "詳細", cook_path(cook), class: "btn btn-sm btn-success"
      - else
        p.text-center お気に入りはありません

app/views/cooks/dutch_oven.html.slim
- content_for(:title, 'ダッチオーブン料理 | CamFoo')
div.dutch-image
  div.bg-rgba
    h2 DutchOven cooks
= render "cooks/shared/index_form", cooks: @cooks_dutch_oven

app/views/cooks/edit.html.slim
- content_for(:title, '投稿編集 | CamFoo')
div.edit-image
  div.bg-rgba
    h2 Edit recipe
= render "cooks/shared/cook_form", cook: @cook

app/views/cooks/index.html.slim
- content_for(:title, 'キャンプご飯一覧 | CamFoo')
div.index-image
  div.bg-rgba
    h2 Index
= render 'cooks/shared/index_form', cooks: @cooks

app/views/cooks/net.html.slim
- content_for(:title, '網料理 | CamFoo')
div.net-image
  div.bg-rgba
    h2 Net cooks
= render "cooks/shared/index_form", cooks: @cooks_net

app/views/cooks/new.html.slim
- content_for(:title, '新規投稿 | CamFoo')
div.new-image
  div.bg-rgba
    h2 Post recipe
= render "cooks/shared/cook_form", cook: @cook

app/views/cooks/other.html.slim
- content_for(:title, 'その他料理 | CamFoo')
div.other-image
  div.bg-rgba
    h2 Other cooks
= render "cooks/shared/index_form", cooks: @cooks_other

app/views/cooks/pan.html.slim
- content_for(:title, 'フライパン料理 | CamFoo')
div.pan-image
  div.bg-rgba
    h2 Pan cooks
= render "cooks/shared/index_form", cooks: @cooks_pan

app/views/cooks/plate.html.slim
- content_for(:title, '鉄板料理 | CamFoo')
div.plate-image
  div.bg-rgba
    h2 Iron plate cooks
= render "cooks/shared/index_form", cooks: @cooks_plate

app/views/cooks/pot.html.slim
- content_for(:title, '鍋料理 | CamFoo')
div.pot-image
  div.bg-rgba
    h2 Pot cooks
= render "cooks/shared/index_form", cooks: @cooks_pot

app/views/cooks/rank.html.slim
- content_for(:title, '総合いいねランキング | CamFoo')
div.rank-image
  div.bg-rgba
    h2 総合いいねランキング
div.ranking-change.pr-5 = link_to "週間ランキングはこちら", weekly_rank_cooks_path
= render "cooks/shared/rank"

app/views/cooks/search_index.html.slim
div style="height: 200px;"
  div
    h2 style="line-height: 200px;" 検索結果
= render 'cooks/shared/index_form', cooks: @search_cooks

app/views/cooks/show.html.slim
- content_for(:title, '投稿詳細 | CamFoo')
div.show-image
  div.bg-rgba
    h2 Recipe

div
  div.btn-show
    div
      - if @cook.user == current_user
        = link_to "編集する", edit_cook_path(@cook) ,class: "btn btn-sm btn-dark py-1"
        <span>&emsp;</span>
        = link_to "削除する", cook_path(@cook) ,class: "btn btn-danger btn-sm py-1", method: :delete, data:{ confirm: '本当に削除して良いですか?',cancel: 'やめる',commit: '削除する'}, title: '削除確認'

  h4.recipe-title = @cook.name
  div.recipe-container
    section.title-box-show
      = attachment_image_tag @cook, :image, :fill, 400, 250
      <br>
      div
        span 調理時間:
        = @cook.cooking_time
        | 分
        <br>
        span ジャンル:
        = @cook.cook_genre_i18n
        <br>
        span 調理道具:
        = @cook.cook_item_i18n
        <br>
    section class="material-box-show #{@cook.id}"
      p = @cook.comment
      div.material-tag.text-center.py-0
        | 材料
      <br>
      table.table.table-sm.w-100
        thead
            tr
              th 食材・調味料
              th 分量
        tbody.border-bottom
          - @materials.each do |material|
            tr
              td = material.material
              td = material.qty
          <br>
      span.like-btn = render "likes/like", obj: @cook
      span.bookmark-btn = render "bookmarks/bookmark", obj: @cook

  div.cooking-method-box
    h4 作り方
    div = simple_format(@cook.cooking_method)

app/views/cooks/weekly_rank.html.slim
- content_for(:title, '週間いいねランキング | CamFoo')
div.rank-image
  div.bg-rgba
    h2 週間いいねランキング
div.text-right.pr-5.ranking-period
  | ※期間:
  = 0.days.ago.prev_week.to_s(:datetime_jp)
  | 〜
  = 0.days.ago.prev_week(:sunday).to_s(:datetime_jp)
div.ranking-change.pr-5
  = link_to "総合ランキングに戻る", rank_cooks_path
- if @ranks.present?
  = render "cooks/shared/rank"