config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:show, :edit, :update, :destroy]
  get 'users' => 'users#dummy'
  root 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#new_guest' # ゲストログイン用
  resources :cooks do
    collection do
      get 'net'
      get 'plate'
      get 'pan'
      get 'dutch_oven'
      get 'pot'
      get 'other'
      get 'rank'
      get 'weekly_rank'
      get 'bookmark'
      get 'search_index'
    end
    resource :likes, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  resources :notifications, only: [:index] do
    collection do
      delete "all_destroy"
    end
  end
  resources :articles, only: [:index, :show]
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :cook, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

  def update_is_checked_and_save
    is_checked = true if visitor_id == visited_id
    save if self.valid?
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(is_checked: false).each do |notification|
      notification.update_attributes(is_checked: true)
    end
  end

  def all_destroy
    redirect_to request.referrer if current_user.passive_notifications.destroy_all
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(is_checked: false)
  end
end

app/views/notifications/index.html.slim
- content_for(:title, '通知 | CamFoo')
div.notification-image
  div.bg-rgba
    h2 Notification

div.container.mt-3
  div.row
    div.col-10.offset-1
      - notifications = @notifications.where.not(visitor_id: current_user.id)
      - if notifications.exists?
        div.mb-3.w-75.mx-auto
          span
            = link_to all_destroy_notifications_path, method: :delete, data:{ confirm: '本当に通知を空にして良いですか?',cancel: 'やめる',commit: '空にする'}, title: '削除確認', class: "text-white text-decoration-none" do
              i.fas.fa-trash-alt.text-white.btn.btn-danger 通知を空にする

        table.table.text-white.w-75.m-auto
          tbody
            - notifications.each do |notification|
              tr
                td
                  = notification.visitor.account
                  <span>&emsp;</span>
                  span さんが
                  - case notification.action
                    - when 'like' then
                      = link_to "あなたの投稿に", cook_path(notification.cook)
                      span いいねしました
                      div.d-flex.justify-content-end
                        span = notification.created_at.strftime("%Y/%m/%d")
        div.paginate = paginate @notifications
      - else
        p.text-center 通知はありません